### PR TITLE
Mistake from last Pull Request

### PR DESCRIPTION
**Pull request by pixelated-au**
Hi, sorry, I copied and pasted the wrong piece of code yesterday; breaking the integration 😩. This is the correct one. Tested and working!

### CODE REVIEW

**Comment by dannyvankooten** [comment]
Hello @pixelated-au,

I noticed that the new PR is using the short array notation, which is a PHP 5.4 feature whereas our plugin is still supposed to support PHP 5.2 (although not recommended). Can you please switch the PR back to use `array( ... )` instead of `[ ... ]`?

**Comment by pixelated-au** [comment]
Doh! I couldn’t figure out why it was failing. I’ll get onto it asap!

**Comment by pixelated-au** [comment]
Hi @dannyvankooten did you require any other changes to this PR? 😊 I know Travis is still failing but I'm not sure it's related to my patch but let me know if it is 👍

**Comment by strayobject** [comment]
Just a random comment, but it would be great if you followed WP code style. @pixelated-au please, check the code you are overwriting for hints (spacing around functions and params, use of tabs instead of spaces, etc).

**Pull request merged**
