### PR TITLE
AMP compatibility

### LINKED ISSUE #457: Support AMP
MC4WP gives errors on AMP compatibility: https://search.google.com/test/amp

Please inform: 
https://secure.helpscout.net/conversation/401579136/11203/?folderId=253120
https://wordpress.org/support/topic/amp-error-invalid-value-for-html-attribute-style-in-tag-label/

### PR DESCRIPTION
**Pull request by claudiulodro**
This PR adds AMP-compatibility to the forms. This is accomplished by adding the necessary response templates to forms and a new API endpoint that processes a form and returns its status.

If this needs `@since` docblock, you don't like where I've put the code, or any of the composer stuff needs to be removed, let me know.

Closes #457 

## To test
1. Install and activate [the official AMP plugin](https://wordpress.org/plugins/amp/). In AMP > General > Website Mode settings, set the mode to either Transitional or Standard.
2. Create a form and add it to a page with the mc4wp shortcode.
Screen Shot 2020-01-22 at 11 34 30 AM
3. In AMP and non-AMP mode try out the form. You should get the same look and behavior in each.
Screen Shot 2020-01-22 at 11 35 15 AM

### CODE REVIEW

**Comment by dannyvankooten** [comment]
:tada: Thank you so much for submitting this as a PR @claudiulodro, I hope to look at this in detail on Monday.

**Comment by dannyvankooten** [comment]
All looked very good to me @claudiulodro. Only modifications I did were super specific to our plugin, like that our original form listener would respond with a `Location: ...` header when a form had a redirect URL configured, or that HTML in the success message would be escaped. 

Thanks again for this PR, much appreciated!

**Comment by westonruter** [comment]
This is great. Once this is released we'll add it to https://amp-wp.org/ecosystem/plugins/

**Comment by dannyvankooten** [comment]
This was just pushed to WordPress.org in version 4.7.5 of Mailchimp for WordPress. Thanks again @claudiulodro!

@westonruter That'd be great!

**Comment by max23468** [comment]
I'm using 4.7.5 but still I get error for MC4WP with AMP. Wasn't this fixed?

**Pull request merged**
